spring:
  datasource:
    url: jdbc:h2:~/recommendation;MODE=MySQL;DATABASE_TO_LOWER=TRUE;FILE_LOCK=FILE;
    driverClassName: org.h2.Driver
    username: sa
    password:
    h2:
      console:
        enabled: true
        path: /h2-console
  sql:
    init:
      mode: always
      schema-locations: classpath:data/schema.sql
      data-locations: classpath:data/data.sql
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: 127.0.0.1
      port: 6379


